image: hseeberger/scala-sbt:11.0.3_1.2.8_2.12.8

stages:
  - test
  - release

test:
  stage: test
  script:
    - sbt clean test
  variables:
    CI: "true"

release on bintray:
  stage: release
  only:
    refs:
      - master
  script:
    - sbt "release skip-tests with-defaults"

before_script:
  - gpg --import  <(echo "$GITLAB_PGP_PRIVATE_KEY")
  - source <(gpg -q --decrypt secrets-env.sh.secret)