include:
  - 'https://colisweb-open-source.gitlab.io/ci-common/templates/scala.yml'

.opentracing-test:
  extends: .sbt-test
  tags: []

test scala-opentracing-amqp:
  extends: .opentracing-test

test scala-opentracing-core:
  extends: .opentracing-test

test scala-opentracing-context:
  extends: .opentracing-test

test scala-opentracing-http4s-server-tapir:
  extends: .opentracing-test

test scala-opentracing-http4s-client-blaze:
  extends: .opentracing-test

test scala-opentracing-http4s-test:
  extends: .opentracing-test

version:
  extends: .version
  tags: []

publish on sonatype:
  extends: .sonatype-publish
  tags: []

