stages:
  - build
  - test
  - release

compile scala sources:
  stage: build
  script:
  - rm -rf sbt-stash/
  - sbt clean test:compile stash
  artifacts:
    paths:
    - sbt-stash
    expire_in: 2 hrs

test:
  stage: test
  script:
    - sbt stashApply test
  variables:
    CI: "true"

release on bintray:
  stage: release
  only:
    refs:
      - master
  script:
    - gpg --import  <(echo "$GITLAB_PGP_PRIVATE_KEY")
    - git secret reveal
    - source secrets-env.sh
    - sbt stashApply "release skip-tests with-defaults"