image: hseeberger/scala-sbt:11.0.3_1.2.8_2.12.8

stages:
  - test
  - release

test:
  stage: test
  script:
    - sbt clean test
  variables:
    CI: "true"

release on bintray:
  stage: release
  only:
    refs:
      - master
      - refacto/release-process
  script:
    - git config --global user.email $GITLAB_USER_EMAIL
    - git config --global user.name "$GITLAB_USER_NAME"
    - git checkout $CI_COMMIT_REF_NAME 
    - sbt -Dbintray.user=gitlab-ci -Dbintray.pass=$BINTRAY_PASS "release skip-tests with-defaults"
    - git rebase $CI_COMMIT_REF_NAME develop
    - git push origin develop --force-with-lease

before_script:
  - gpg --import  <(echo "$GITLAB_PGP_PRIVATE_KEY")
  - source <(gpg -q --decrypt secrets-env.sh.secret)